base_url = "https://ad.oliviero.xyz"
title = "Adriano Oliviero"
description = "My Portfolio"
default_language = "en"

[extra]
author = "Adriano Oliviero"
role = "Computer Engineering Student"
github = "https://github.com/ad-oliviero"
email = "adrianoliviero23@gmail.com"
avatar_url = "https://avatars.githubusercontent.com/u/41623496?v=4&s=400"
